trigger:
- master

variables:
  tag: $(Build.BuildId)
  latestTag: latest

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build job
    pool:
      vmImage: ubuntu-latest

    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'rg-webapp-01'
        repository: 'app1nginx'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: | 
          $(tag)
          $(latestTag)

    - task: CopyFiles@2
      displayName: Copy Kubernetes manifests
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
        OverWrite: true

    - task: PublishBuildArtifacts@1
      displayName: Publish manifests
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'kube-manifests'
        publishLocation: 'Container'
